package by.mitsko.selenium;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

public class MyMailSecondTest {
	 private WebDriver driver;
		
	 
	 @BeforeTest
	 public void openPage (){
		 System.setProperty("webdriver.chrome.driver", "d:/driver/chromedriver.exe");
		  WebDriver driver = new ChromeDriver();
		      		  
		  driver.get("https://mail.ru");
	 }
	 
	 
		
     @Test
     public void sending() throws InterruptedException   {
		  
		  
		  
		  WebElement login = driver.findElement(By.id("mailbox:login"));
	      login.sendKeys("mariyamitko");
	      
	      WebElement password = driver.findElement(By.id("mailbox:password"));
	      password.sendKeys("ZcysqGthtw13");
	      
	      WebElement submit = driver.findElement(By.id("mailbox:submit"));
	      submit.click();
	      Thread.sleep(10000);
	      
	      WebElement myLetter = driver.findElement(By.xpath("//*[@id='b-letters']/div/div[2]/div/div[2]/div[1]/div/a/div[4]"));
		  myLetter.click();
		  
		  
		  
		  
		  Thread.sleep(10000);
		  WebElement contact = driver.findElement(By.xpath("//*[@id='b-letters']/div/div[2]/div/div[2]/div[1]/div/a/div[4]/div[3]/div[2]"));
		  Assert.assertEquals(contact.getText(), "Артум Каптур");
		  
			  
		  Thread.sleep(10000);
		  WebElement answer = driver.findElement(By.xpath("//*[@id='b-toolbar__right']/div[3]/div[1]/div/div[2]/div[2]/div/div[1]/span"));
		  answer.click();
		  
		  WebElement fr = driver.findElement(By.xpath("//iframe[@allowtransparency='true']"));
		  driver.switchTo().frame(fr);
		  
		  WebElement text = driver.findElement(By.xpath("//*[@id='tinymce']"));
		  text.sendKeys("Hello, my dear friend! This is my answer that was generated by SeleniumWebDriver");
          
		  driver.switchTo().defaultContent();
		  
		  Thread.sleep(5000);
		  WebElement send = driver.findElement(By.xpath("//*[@id='b-toolbar__right']/div[4]/div/div[2]/div[1]/div/span"));
		  send.click();
		  
		  
		  
		  
		  		  
		  WebElement myLetter2 = driver.findElement(By.xpath("//*[@id='b-letters']/div/div[2]/div/div[2]/div[1]/div/a/div[4]"));
		  myLetter2.click();
		  		  
		  Thread.sleep(10000);
		  WebElement contact2 = driver.findElement(By.xpath("//*[@id='b-letters']/div/div[2]/div/div[2]/div[1]/div/a/div[4]/div[3]/div[2]"));
		  Assert.assertEquals(contact2.getText(), "Артум Каптур");
		  
		  Thread.sleep(10000);
		  WebElement answer2 = driver.findElement(By.xpath("//*[@id='b-toolbar__right']/div[3]/div[1]/div/div[2]/div[2]/div/div[1]/span"));
		  answer2.click();
		  
		  WebElement fr2 = driver.findElement(By.xpath("//iframe[@allowtransparency='true']"));
		  driver.switchTo().frame(fr2);
		  
		  WebElement text2 = driver.findElement(By.xpath("//*[@id='tinymce']"));
		  text2.sendKeys("Hello, my dear friend! What a beautiful day!");
          
		  driver.switchTo().defaultContent();
		  
		  Thread.sleep(5000);
		  WebElement send2 = driver.findElement(By.xpath("//*[@id='b-toolbar__right']/div[4]/div/div[2]/div[1]/div/span"));
		  send2.click();
		  
		  
		  
		  
		  
		  WebElement myLetter3 = driver.findElement(By.xpath("//*[@id='b-letters']/div/div[2]/div/div[2]/div[1]/div/a/div[4]"));
		  myLetter3.click();
		  
		  Thread.sleep(10000);
		  WebElement contact3 = driver.findElement(By.xpath("//*[@id='b-letters']/div/div[2]/div/div[2]/div[1]/div/a/div[4]/div[3]/div[2]"));
		  Assert.assertEquals(contact3.getText(), "Артум Каптур");
		                                                     
		  
		  Thread.sleep(10000);
		  WebElement answer3 = driver.findElement(By.xpath("//*[@id='b-toolbar__right']/div[3]/div[1]/div/div[2]/div[2]/div/div[1]/span"));
		  answer3.click();
		  
		  WebElement fr3 = driver.findElement(By.xpath("//iframe[@allowtransparency='true']"));
		  driver.switchTo().frame(fr3);
		  
		  WebElement text3 = driver.findElement(By.xpath("//*[@id='tinymce']"));
		  text3.sendKeys("Hello, my dear friend! What a beautiful day!");
          
		  driver.switchTo().defaultContent();
		  
		  Thread.sleep(5000);
		  WebElement send3 = driver.findElement(By.xpath("//*[@id='b-toolbar__right']/div[4]/div/div[2]/div[1]/div/span"));
		  send3.click();
	}
     
     @AfterTest
	 public void closePage (){
    	 driver.close();
    	 
     }
}